nodejs/corepack

.gitignore
mkshims.ts

There are no cmd shims for Windows since `@zkochan/cmd-shim` only makes those, unless explicitly enabled, when running on Windows.
Explicitly enable creating cmd shims

fix: generate cmd shims

---

.github/workflows/build.yml
.github/workflows/nodejs.yml
package.json

The build script is trying to use `yarn` to run `webpack` but because of the order the "binjumpers" are created in Yarn, that points to the local one which doesn't exist yet so it fails.
Use the binaries directly without calling Yarn

build: don't try to use yarn before building it

---

sources/Engine.ts
sources/commands/Prepare.ts
sources/fsUtils.ts
sources/main.ts
sources/pmmUtils.ts

The use of symlinks caused permission issues on Windows, and they aren't really necessary as we can just spawn the files directly
Avoid symlinks and just spawn the files directly

fix: avoid symlinks to work on Windows

---

.vscode/settings.json
mkshims.ts
sources/main.ts

The corepack binary wasn't properly detecting when it was being spawned by itself when installed via npm. This diff fixes that by removing the check used to ensure that the CLI only ran when invoked directly from within the repo, or indirectly by one of the shims.
Fixes #12

Fixes the corepack binary

---

package.json
sources/specUtils.ts

Ranges are a tad dangerous because there's no telling which version will be installed exactly. While they are supposed to be compatible, the pros and cons are somewhat unbalanced at the moment: the risk of a regression is higher than the potential size gain, because Corepack doesn't cover npm at the moment - which is the main case where deduplication would matter.
It's better to restrict the `packageManager` field to strict semver versions for this first iteration and see if there's a need for ranges (which would be possible to add in a minor) than do the opposite and have to make a backward-incompatible change later down the road.

Restricts to exact versions

---

mkshims.ts

The `corepack` shim didn't exist in the published archive (since `mkshim` was only iterating over the package manager binaries). This fixes that.

Adds the missing corepack shim

---

README.md
sources/commands/Disable.ts
sources/commands/Enable.ts
sources/types.ts
tests/Disable.test.ts
tests/Enable.test.ts

The npm shim was accidentally being set when calling `corepack enable` with no parameters. Since my personal policy is to leave the npm team choose how they want to integrate with Corepack, let's disable this for now until they explicitly agree to have npm installed by Corepack as well.
For experimentation purposes I've left the ability to explicitly request the npm shim by running `corepack enable npm`.

Prevents npm from being accidentally set

---

package.json

supersedes PR #30; fixes #28 see references:
- https://github.com/nodejs/corepack#license-mit
- https://github.com/nodejs/corepack/blob/main/LICENSE.md

add license & GitHub info to package.json

---

README.md

The `pmm` was refactored to `corepack` (9809b8f856cba5e91a1ec54f595073373696440d). However, `pmm` has still been used in README. I think it is better to change it. Also, `dist/corepack` does not have the `--version` option, so I fixed it with `--help`.

docs: fix pmm -> corepack in Contributing

---

sources/Engine.ts

Prereleases with a major higher than the declared range doesn't match
Use `semverUtils.satisfiesWithPrereleases` to find matches

fix: handle prereleases

---

config.json
package.json
sources/Engine.ts
sources/main.ts
sources/pmmUtils.ts
sources/types.ts

The following diff enables the ability to run:
```
corepack yarn@1.22.0 yarn ...
```
In other words, it's now possible to force use a specific version if needed. This is useful for testing purposes, but is also used in Yarn's init workflow (which requires to jump through some hoops).
Additionally, this syntax supports tags (but only this syntax supports it; it's still not possible to set `"packageManager": "canary"` in your package.json):
```
corepack yarn@canary yarn ...
```

Adds support for executing arbitrary versions of packages managers

---

package.json
sources/main.ts

The version wasn't properly set, so running `corepack -v` didn't work.

Fixes the displayed version number

---

mkshims.ts

The `vcc.js` file is just v8-compile-cache compiled to a single JS bundle. Since it's located in the `dist` directory, `mkshims` incorrectly generated shims for it (which isn't useful, as its only purpose is to be required by the other jumpers).
This diff makes sure that this file is excluded from the shim generation.

Removes vcc from the binaries

---

sources/main.ts

https://github.com/nodejs/corepack/pull/42 used `eval` to get the current corepack version which doesn't work if the path to corepack isn't `.../node_modules/corepack`
Use a statically analysable `require`

fix: avoid using `eval` to get the corepack version

---

README.md
mkshims.ts
sources/Engine.ts
sources/main.ts
tests/main.test.ts

It was already possible to invoke any version of the configured package manager by using the `corepack` CLI itself (ie by calling `corepack pnpm pnpx ...`), but the syntax was needlessly verbose (just mentioning `pnpx` should have been enough to know that the expected package manager was `pnpm`). This is now fixed, and properly documented.
Also fixes calling `corepack` with no argument (still have to add a test for that).
Fixes #44

Simplifies package manager commands from the Corepack CLI

---

README.md

This PR is effectively `s/Node/Node.js/g`. The project's official name is "Node.js" not "Node".

docs: fix README to use the project's actual name

---

sources/commands/Disable.ts
sources/commands/Enable.ts

The help message references the wrong option name.
Fixes #80

Fixes invalid option name in Enable/Disable's help

---

.gitignore

When running `jest --collect-coverage` a `coverage` folder is created,
which should not be committed.

tools: add `coverage` folder to `.gitignore`

---

package.json
sources/Engine.ts
sources/_entryPoint.ts
sources/commands/Enable.ts
sources/corepackUtils.ts
sources/main.ts
sources/module.d.ts
sources/nodeUtils.ts
tests/_runCli.ts
tsconfig.json
webpack.config.js

While looking into improving Yarn's startup time, we've observed the fact that corepack adds extra overhead by spawning a new process to run the invoked binary.
This PR makes `corepack` load binaries in the same process, removing the `spawn` indirection and considerably improving the startup time:
<table>
<tr>
<td>package-manager --version
<td>Before
<td>After
<tr>
<td>yarn@3.2.0
<td>183.1 ms
<td>159.7 ms
<tr>
<td>pnpm@6.29.1
<td>92.0 ms
<td>69.8 ms
<tr>
<td>npm@8.1.0
<td>160.8 ms
<td>131.6 ms
</table>
The way it achieves this is by modifying `process.{argv,execArgv}` and `process.mainModule` (and the module cache to make sure that `require.main === module` keeps working) to trick the binary into thinking that it was …

perf: load binaries in the same process

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
sources/commands/Prepare.ts
tests/main.test.ts

Fixes #96
The existing implementation of `prepare` iterates over an array of `string | Descriptor` requests and only looks up the project version when `typeof request === 'undefined'`, which is never true. This wasn't caught by the test suite since the network was left enabled.
I've updated the command to instead look up the project spec when the specs list is empty, before the loop starts.

Fixes `corepack prepare` when no additional arguments are passed

---

.github/workflows/ci.yml
package.json

On a merge commit, `HEAD^` refers to the base branch commit, so we can use it instead of `git merge-base origin/"$TARGET_BRANCH" HEAD`. The upside is we don't have to fetch the whole repo anymore, which should speed up the CI.

ci: simplify `Testing chores` job

---

sources/corepackUtils.ts

This is useful when `DEBUG=corepack` is set because it tells you where it installed to.
Alternatively, we could add this to the `Install finished` debug line at the end.
- Related to #75

chore: include install directory in debug log

---

.github/workflows/sync.yml

Currently the Sync workflow is failing because GitHub Actions do not have permission to commit to the `main` branch. Instead, we can ask it to create a PR, which has the upside of making sure the job is not committing ill-formed data to the `main` branch.
Other changes:
- Schedule to run the job once a week (I think it's plenty) instead of daily.
- Use the latest Node.js LTS version rather than v14.x.
- Use `git show` instead of a temporary file.

ci: fix the Sync workflow

---

.github/workflows/ci.yml

- Use the latest LTS Node.js version available rather than having an arbitrary `14` for `Testing chores` job.
- Add Node.js 16.x and 18.x to the test matrix.

ci: test on all supported Node.js versions

---

.github/workflows/sync.yml

> I think we should use https://github.com/gr2m/create-or-update-pull-request-action/commit/6720400cad8e74d7adc64640e4e6ea6748b83d8f instead.
https://github.com/gr2m/create-or-update-pull-request-action/blob/6720400cad8e74d7adc64640e4e6ea6748b83d8f/dist/index.js
> There's no `/dist/` in their master branch.
_Originally posted by @LiviaMedeiros in https://github.com/nodejs/node/issues/43377#issuecomment-1152883511_

chore: fix `Version Sync` action

---

.github/workflows/publish.yml
.github/workflows/sync.yml

According to https://github.com/google-github-actions/release-please-action#configuration, `bump-minor-pre-major` option can be used to stay on `0.x` even if we introduce breaking changes.
According to https://github.com/googleapis/release-please#release-please-bot-does-not-create-a-release-pr-why, we want to use `feat` or `fix` for the automation that updates the package manager versions, otherwise release-please won't create a PR.

chore: fix GHA automations

---

package.json
yarn.lock

The package.json contains a `bin` entry point to `dist/yarn.js`. As a result, when a script runs, this bin entry is injected into the PATH. While it usually works fine, in this case the bin is called `yarn`, so it overrides the `yarn` binary usually present in the PATH and that `prepack` calls to run `yarn build`. Given that `dist/yarn.js` doesn't exist yet at this point in time, the packing fails.
This diff fixes that by only setting the `bin` entries inside the published package, so that they don't override the local values during development.

Only set bins on pack

---

.github/workflows/sync.yml

Useful if https://github.com/nodejs/corepack/pull/133 lands.

chore: add sha1 to default versions when available

---

sources/commands/Prepare.ts
sources/specUtils.ts

This would allow to keep up-to-date the "default" version of each package managers.
Fixes: https://github.com/nodejs/corepack/issues/72

feat: add support for tags and ranges in `prepare` command

---

sources/corepackUtils.ts

If a large number of versions are cached on the host system, trying to read the whole cache at once can be quite memory intensive. Instead, we can use an iterative approach that doesn't hold the whole directory content in memory.

fix: streamline cache exploration

---

package.json
yarn.lock

The upgrade of the Yarn version should fix the failure on Node.js 18.x.

chore(deps): upgrade all dependencies

---

.github/workflows/sync.yml

GHA uses OpenSSL 3.x, not 1.1.1, so the output was different on my machine.
Refs: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md

chore(ci): fix `Version Sync` workflow

---

DESIGN.md

#140
I just did a find and replace of "engines.pm to packageManager". Also it seems the version has to be 2.0.0 not ^2.0.0
I don't know whether anything else has changed since this document was written.
Maybe "Envisioned workflow" etc. needs to be changed if it is no longer a proposal and is now released.

Update DESIGN.md s/engines.pm/packageManager/

---

.github/workflows/sync.yml

Node.js' Version Sync workflow runs on Sunday, it makes sense to run
our own before that so we have to time to publish a release on time.

chore(ci): run `Version Sync` on Friday

---

README.md
sources/folderUtils.ts

Fixes: https://github.com/nodejs/corepack/issues/145
Refs: https://github.com/nodejs/node/issues/43859

feat: do not use `~/.node` as default value for `COREPACK_HOME`

---

README.md
config.json
sources/Engine.ts
sources/corepackUtils.ts
sources/types.ts
tests/main.test.ts

This PR ensures that fresh install of Corepack would always use the latest available version for a given package manager.
We probably want to add a command to clear the cache for `lastKnownGood` version (although I think that's more or less what `corepack prepare` is doing), and/or have a expiracy date for the `lastKnownGood` version to make Corepack update the default version from time to time.
Fixes: https://github.com/nodejs/corepack/issues/93

feat: download the latest version instead of a pinned one

---

tests/_runCli.ts

`runCli` uses the `exit` event to know when a process finishes executing but the `exit` event can be called before the `stdio` streams are flushed which causes a race condition where it sometimes wont get the `stdout` / `stderr` value.
Fixes https://github.com/nodejs/corepack/runs/7926771653?check_suite_focus=true#step:8:32
Switch from the `exit` event to the `close` event which is called after the `stdio` streams are closed.

test: wait for stdio streams of process to close

---

README.md
sources/specUtils.ts
tests/main.test.ts

Fixes: https://github.com/nodejs/corepack/issues/157

feat: add `COREPACK_ENABLE_STRICT` env variable

---

README.md

fixes #187 
Disclaimer: this is a quick pass from someone not yet familiar with the software, but I think it's correct and an improvement over the status quo.

Add package configuration instruction to readme

---

README.md
sources/corepackUtils.ts
sources/npmRegistryUtils.ts
tests/npmRegistryUtils.test.ts

This adds support per #66 
Resolves https://github.com/nodejs/corepack/issues/66

feat: add support for configurable registries and applicable authentication options

---

mkshims.ts
sources/corepackUtils.ts
sources/nodeUtils.ts
webpack.config.js

After the changes in https://github.com/nodejs/corepack/pull/97 we no longer need a path to `v8-compile-cache` so we can just import it normally.

refactor: simplify `v8-compile-cache` setup

---

mkshims.ts
package.json
webpack.config.js
yarn.lock

Corepack is built in Webpack's development mode which causes Webpack to output files with long filenames.
Fixes https://github.com/nodejs/corepack/issues/130
Change it to build in production mode but disable minimizing so the code is still somewhat readable.
The bundle size also improved a bit:
```diff
$ du -s dist
- 2434    dist
+ 2170    dist
```

build: enable production mode

---

.eslintignore
genlist.ts
package.json
sources/commands/Disable.ts
sources/fsUtils.ts
tests/recordRequests.js

The `lint` script doesn't match any files.
Updated it to match all files and then linted them.
Depends on https://github.com/nodejs/corepack/pull/222 which works around https://github.com/arcanis/eslint-plugin-arca/issues/26

chore: fix linting

---

package.json
tsconfig.json
webpack.config.js

[v0.11.0](https://github.com/nodejs/corepack/releases/tag/v0.11.0) (specifically https://github.com/nodejs/corepack/pull/100) dropped support for Node.js v12 and raised the bar to Node.js v14.14.0 due to https://github.com/nodejs/corepack/blob/82a6715702ac49687aa8b731efb5971bcdeac0a3/sources/fsUtils.ts#L4 (https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fspromisesrmpath-options) but this wasn't written down as far as I can tell.
Addresses https://github.com/nodejs/corepack/pull/100#pullrequestreview-945341129
Added `engines.node` to `package.json` to document the minimum version.

chore: add `engines.node` to `package.json`

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/update-nock-files.yml

Resolve #233 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: echo "::set-output name=result::$(git --no-pager diff --quiet -- tests/nock || echo "yes")"
```
```yml
run: echo "::set-output name=dir::$(corepack yarn config get cacheFolder)""
```
**TO-BE**
```yml
run: echo "result=$(git --no-pager diff --quiet -- tests/nock || echo …
```

chore: Replace deprecated command with environment file

---

README.md
sources/httpUtils.ts

Adding a note about DNS to the generic HTTP error message

---

sources/httpUtils.ts

chore: report error url on fetchUrlStream exception

---

mkshims.ts
package.json
sources/_cli.ts
sources/_entryPoint.ts
sources/_lib.ts

The entry point for the Corepack CLI and the (internal) API is the same file forcing the use of `process.mainModule === module` to check which one should be used.
Create two separate entry points, one for the CLI and one for the API.

refactor: separate library and CLI entry point

---

.github/workflows/ci.yml
.github/workflows/update-nock-files.yml
README.md
package.json
tsconfig.json

BREAKING CHANGE: remove support for Node.js 14.x

chore: update supported Node.js versions

---

README.md

This issue is more widespread than I initially thought and some issues arise directly from DNS resolution of ipv6 domains, so I wanted to update the docs to call that out specifically

Updating DNS troubleshooting to mention ipv6

---

package.json
yarn.lock

This is to update the indirect vm2 dependency and resolve some dependabot alerts.

chore: update dev dependency proxy-agent to 6.2.2

---

package.json
yarn.lock

Node.js v20.6 [changed the ESM loader a bit](https://github.com/nodejs/node/pull/47999) so the version of Yarn used by Corepack needs to be updated to a version containing https://github.com/yarnpkg/berry/pull/5677.
Fixes the install failing on Node.js v20.
Ref https://github.com/nodejs/corepack/pull/307#issuecomment-1714464178

chore: update Yarn

---

sources/npmRegistryUtils.ts

Hello! 👋🏼 
I just ran into an issue where our custom registry doesn't support the `Accept` header value of `application/vnd.npm.install-v1+json`. By providing a fallback to `application/json`, `corepack` can support custom registries that don't support the `application/vnd.npm.install-v1+json` value.
I followed the [article linked in the comments above this code change](https://github.com/npm/registry/blob/cfe04736f34db9274a780184d1cdb2fb3e4ead2a/docs/responses/package-metadata.md) where it is suggested to use `application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*` for fallback. I opted to drop the `*/*` since this is a json fetch implementation but feel free to change it. 
This was also referenced in #296 where @arcanis mentioned this would likely be fine.

feat: allow fallback to `application/json` for custom registries

---

config.json

I added a new `aliases` field to https://repo.yarnpkg.com/tags which contain all of `stable`, `canary`, and `latest`. We can use this field in the new configuration so that we support `latest` without changing anything to whatever may be relying on the content of the `latest` field.

Switches Yarn to the "aliases" field

---

sources/httpUtils.ts
tests/httpUtils.test.ts

Some registries will redirect and return with 302;
It will cause corepack error；
```bash
Internal Error: Server answered with HTTP 302
```
This PR helps redirections supported when a request responds with a 302 or 301 status code.
Associated with:  
https://github.com/nodejs/corepack/issues/302
https://github.com/nodejs/corepack/issues/336

feat: Support redirections

---

config.json
sources/Engine.ts
sources/corepackUtils.ts
sources/types.ts

It's been mentioned a couple of times that Yarn publishing its versions on its own was inconvenient for people using private npm mirrors. I'd prefer to keep using our store by default, but it makes sense to offer a way to fallback to the npm store when requested. This diff changes the logic so that we use the `@yarnpkg/cli-dist` package when the `COREPACK_NPM_REGISTRY` variable is set. It should be backward-compatible, since the `registry` field is still the same.
Fixes #337

Fallbacks to npm when COREPACK_NPM_REGISTRY is set

---

tests/main.test.ts

For some reason this test times out quite frequently on Windows CI. Hopefully if we give it more time to succeed, and we won't need to restart Windows CI as often.

chore(tests): increase timeout to get more green on Windows CI

---

sources/folderUtils.ts

Since https://github.com/nodejs/corepack/pull/291 was merged Corepack wont reuse the package managers installed by old Corepack versions so no need to keep the migration.
Ref https://github.com/nodejs/corepack/pull/372#issuecomment-1925471159

feat!: remove old install folder migration

---

sources/Engine.ts
sources/corepackUtils.ts
sources/folderUtils.ts
tests/main.test.ts

https://github.com/nodejs/corepack/pull/291 introduced an unsafe remove which sometimes break parallel installs.

fix: remove unsafe remove of install folder

---

package.json

We do not support EOL versions.

chore!: remove Node.js 19.x from the range of supported versions

---

package.json

The range added in https://github.com/nodejs/corepack/pull/375 isn't valid.

fix: use valid semver range for `engines.node`

---

sources/httpUtils.ts

JSON data is (supposedly) rather innocuous, it seems unnecessary to have a prompt for those.
Fixes: https://github.com/nodejs/corepack/issues/380

fix: do not show download prompt when downloading JSON

---

sources/httpUtils.ts
tests/main.test.ts

Very small diff to change:
```
Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.21.tgz.
Do you want to continue? [Y/n] y
1.22.21
```
Into:
```
Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.21.tgz.
Do you want to continue? [Y/n] y
1.22.21
```

Group the prompt together

---

tests/setupTests.js

Fixes https://github.com/nodejs/corepack/issues/377

test: clear all `COREPACK_*` environment variables

---

sources/corepackUtils.ts

Fixes #246
That should fix the problem that windows malicious file analysis blocks the freshly downloaded file.
I couldn't reproduce the error on my side currently, but it should help.

Fix Windows malicious file analysis waiting problem

---

CONTRIBUTING.md

We didn't document the process to add new package managers to Corepack. I added a rough draft based on the discussions we had around the topic lately, feel free to suggest improvements in wording or content.

Adds a note clarifying how to add new package managers

---

README.md
sources/Engine.ts
sources/commands/Base.ts
sources/commands/Up.ts
sources/commands/Use.ts
sources/httpUtils.ts
sources/main.ts
sources/specUtils.ts
tests/main.test.ts

Once Corepack is enabled, someone restarting their container without having pinned the version of the package manager in `packageManager` may use different package manager versions pre-restart and post-restart, due to Corepack always defaulting on the highest release when the package manager isn't pinned (this was strongly requested in https://github.com/nodejs/corepack/issues/93).
However, we want this "dynamic" selection to be slightly tuned down so it only affects projects as they are created - once a project is created or accessed for the first time, the package manager version should remain the same until the user decides otherwise. People in #399 seemed to agree this was the right behaviour, and I don't have very strong objections on that.
This diff implements this logic by checking …

feat: Pins the package manager as it's used for the first time

---

config.json

New projects should use the newest versions when setup. Adding `yarn init` as a transparent command means that people running it will automatically have the `packageManager` field set to `4.1.0+sha...` unless they explicitly opt-out by running `corepack yarn@1 init` instead.
Projects that don't list package managers will still execute Yarn 1.x, and so will other Yarn commands executed from outside any package directory (`yarn config set`, etc).

Marks `yarn init` as a transparent command

---

sources/Engine.ts

Fixes: https://github.com/nodejs/corepack/issues/420

fix: ignore `EROFS` errors

---

sources/corepackUtils.ts
sources/fsUtils.ts

The util was useful when we supported Node.js versions without `fs.promises.rm` but after https://github.com/nodejs/corepack/pull/100 we no longer need it and can call `fs.promises.rm` directly, which we're already doing [elsewhere](https://github.com/nodejs/corepack/blob/f442366c1c00d0c3f388b757c3797504f9a6b62e/sources/commands/Cache.ts#L21).

chore: remove `fsUtils.rimraf`

---

sources/Engine.ts
sources/miscUtils.ts

The code never throws a `Cancellation` error so checking for one is unnecessary.

chore: remove unused `Cancellation` error

---

sources/npmRegistryUtils.ts

It occured to me we don't always need to download the complete set of metadata, sometimes we can limit ourselves to a single version/tag.

fix: download fewer metadata from npm registry

---

tests/_registryServer.mjs

Since https://github.com/nodejs/corepack/pull/436, we now hit different endpoints that the previous tests did not cover.

chore: fix tests on custom registry

---

config.json
sources/corepackUtils.ts
sources/types.ts
tests/main.test.ts

Added `bin` property to `NpmRegistrySpec`. When installing yarn berry from custom registry, it'll only install the bin file and calculate hash of the bin file itself.
Fix #435

feat: download only `yarn.js` from npm

---

package.json
sources/httpUtils.ts
tests/_registryServer.mjs
tests/main.test.ts
yarn.lock

In an attempt to bundle only a subset of Undici code, we forgot to take some side-effect.
Fixes: https://github.com/nodejs/corepack/issues/417
Closes: https://github.com/nodejs/corepack/pull/449

fix: correctly set `Dispatcher` prototype for `ProxyAgent`

---

sources/httpUtils.ts
tests/_registryServer.mjs

Changes auth type header strings to use `Basic` prefix for base64 encoded username:password.
In addition, it seems like an undocumented env var `COREPACK_NPM_USER` is being used in tests, meaning that this value will be `undefined` and the user will always get a 401 as the documented env var is `COREPACK_NPM_USERNAME`.
This bit me when I was using a test to help debug why my COREPACK_NPM_REGISTRY was being ignored when running `yarn --version` in real life.

fix: Incorrect authorization prefix for basic auth, and undocumented env var

---

sources/Engine.ts
sources/corepackUtils.ts
tests/_runCli.ts
tests/main.test.ts

Closes https://github.com/nodejs/corepack/issues/183
Closes https://github.com/nodejs/corepack/issues/422
This PR is separating read and write operations on `lastKnownGood.json`. It will also skip overwriting `lastKnownGood.json` with the same content.
This PR is best reviewed with white space changes ignored due to indentation changes from removing try/catch/finally blocks.
I refactored the read and write operations into self contained functions. The re-use of a `r+` file handle does not work anymore when separating the two kinds of operations.
The content of `lastKnownGood.json` is validated/sanitized when reading. Any consumers can operate on the `Record<string, string>` object directly. This greatly simplified the logic in `activatePackageManager` and …

Separate read and write operations on lastKnownGood.json

---

sources/Engine.ts
tests/main.test.ts

I had to help someone who couldn't understand why they were getting this error message on an empty directory; turned out they had a `package.json` in their home directory (no idea how it got there) that defined a `packageManager` field. I think adding some explanation would help.

fix: add path to `package.json` in error message

---

sources/main.ts
tests/main.test.ts

Calling `executePackageManagerRequest` directly instead of through Clipanion lets Node.js handle printing errors which results in the `cause` property being printed correctly.
Ref https://github.com/nodejs/corepack/issues/458 and others like it.
Ref https://github.com/nodejs/corepack/pull/425#issuecomment-2000189938
Depends on
- https://github.com/nodejs/corepack/pull/428
Performance is roughly the same
```console
$ hyperfine -w 5 "node ./dist-before/yarn.js -v" "node ./dist-after/yarn.js -v"
Benchmark 1: node ./dist-before/yarn.js -v
Time (mean ± σ):     188.0 ms ±   9.9 ms    [User: 204.5 ms, System: 22.3 ms]
Range (min … max):   179.0 ms … 222.1 ms    16 runs
Benchmark 2: node ./dist-after/yarn.js -v
Time (mean ± σ):     186.5 ms ±   7.8 ms    [User: 202.5 ms, System: 22.4 ms]
Range …
```

fix!: call `executePackageManagerRequest` directly

---

sources/httpUtils.ts
tests/_registryServer.mjs

I noticed when using this package, if you set `COREPACK_NPM_REGISTRY`, authentication wasn't working as expected.
After debugging and reading through the code, it appears that when the following code was run:
```
if (typeof input === `string`)
input = new URL(input);
```
`input.username` would become an empty string. This caused `process.env.COREPACK_NPM_USERNAME` to not be used. 
By switching `??` to `||`, the authorization header should now be sent to the registry as expected!

fix: COREPACK_NPM_REGISTRY should allow for username/password auth

---

README.md
sources/corepackUtils.ts
sources/npmRegistryUtils.ts
tests/corepackUtils.test.ts

This PR adds the possibility of setting `COREPACK_INTEGRITY_KEYS` to `0` ~and `false`~ to disable integrity checks.
Fixes: #468

feat: COREPACK_INTEGRITY_KEYS should support `0` and `false` values

---

.github/workflows/update-nock-files.yml

When there are no changes, asking Git to compare the db file directly will always report change even though the actual data stored is the same. Instead, we can compare a SQL dump to detect actual changes.

chore(ci): better check for Nocks changes

---

sources/corepackUtils.ts
tests/_registryServer.mjs

Not all proxies rewrite the tarball URL, and expect the client to do so.
Fixes: https://github.com/nodejs/corepack/issues/498

fix: replace npm registry domain in tarball URL

---

genlist.ts
sources/Engine.ts
sources/commands/Up.ts
sources/corepackUtils.ts
sources/semverUtils.ts
sources/specUtils.ts

By selectively importing only the functions we want, we avoid bundling in the entire semver package, which results in impressive savings of roughly 25 KB.
Before:
```
wmaj@MacBook-Air corepack % yarn build
dist/lib/corepack.cjs  949.5kb
```
After:
```
wmaj@MacBook-Air corepack % yarn build
dist/lib/corepack.cjs  924.7kb
```
It also (minimally) reduces execution time:
```
Benchmark 1: node dist/lib/corepack_before.cjs
Time (mean ± σ):      43.9 ms ±   5.1 ms    [User: 38.9 ms, System: 4.1 ms]
Range (min … max):    42.1 ms …  83.5 ms    65 runs
Benchmark 2: node dist/lib/corepack_after.cjs
Time (mean ± σ):      42.8 ms ±   4.7 ms    [User: 37.9 ms, System: 4.1 ms]
Range (min … max):    40.7 ms …  80.6 ms    67 runs
Summary
node dist/lib/corepack_after.cjs ran
1.03 ± 0.16 times faster than …
```

chore: selectively import required semver functions

---

package.json
yarn.lock

Why bump from 9.x:
better-sqlite3 v9 fails to install on macOS and Node.js 22, which as an upcoming LTS version is likely going to become a primary development tool for contributors.
Why bump to 10.x:
Fixed support for macOS and Node.js 22, general evergreening.
Why bump to 10.x and not 11.x:
better-sqlite3 v11 drops support for Node.js 21.

chore: bump better-sqlite3 to 10.x

---

sources/corepackUtils.ts

Code I removed is literally renameSafe's body, so I replaced it with renameSafe.

chore: use renameSafe where applicable

---

.github/workflows/ci.yml

With Node.js 22 quickly getting closer to LTS, we should be testing Corepack using it.

chore(ci): test on Node.js 22.x

---

package.json
tsconfig.json
yarn.lock

~~Depends on #517~~
Why the change?
ts-node is currently in a bit questionable shape. It barely works with newer versions od Node.js, long-standing bugs are not being addressed, TypeScript + ESM simply does not work. 
I myself was affected by ts-node simply hanging on start during `yarn build` command on Windows.
Why tsx?
While my personal favorite ts-node alternative is tsimp, tsx has seen much higher adoption so far, so I believe it's easier for others to accept it. It also uses esbuild under the hood, which we happen to already use, which results in a considerable drop of number of dependencies.

chore: replace ts-node with tsx

---

.github/workflows/publish.yml

I suggested to use `NODE_AUTH_TOKEN` because that's what was used in https://github.com/nodejs/undici/blob/1a6ab5f61e62a02fc5a0f1da88f1c9973f0baa61/.github/workflows/release.yml#L67, but it looks like that's not working for us. https://github.com/nodejs/remark-preset-lint-node/blob/a99e968ef22cf09bfa9088e7a5d4ff589bfdc2d8/.github/workflows/test-and-release.yml#L67 is using `NPM_TOKEN`, that might be a better choice.

chore(ci): pass `NPM_TOKEN` to `npm publish` step

---

.github/workflows/publish.yml

Reverts nodejs/corepack#527 to fix the release workflow

Revert "chore(ci): pass `NPM_TOKEN` to `npm publish` step"

---

.github/workflows/publish.yml

Reverts nodejs/corepack#520 to fix the release workflow 
/cc @wojtekmaj

Revert "chore: publish to npm with provenance"

---

sources/Engine.ts
sources/corepackUtils.ts
sources/specUtils.ts

Sometimes it can be hard to understand why Corepack behaves the way it does. IMO `DEBUG=corepack` should be more verbose than it currently is, so anyone can follow along e.g. why/how Corepack selects the version of the requested package manager.

fix: make `DEBUG=corepack` more useful

---

package.json
yarn.lock

This bugfix version of semver includes significant performance improvements that I guess we would like to see in corepack.
See: https://github.com/npm/node-semver/pull/726

chore(deps): bump semver from 7.6.2 to 7.6.3

---

sources/npmRegistryUtils.ts
tests/_registryServer.mjs
tests/main.test.ts

Some npm registries do not define an `integrity` field, in which case we can try using the `shasum` field instead.
Fixes: https://github.com/nodejs/corepack/issues/537

fix: fallback to `shasum` when `integrity` is not defined

---

.github/workflows/sync.yml

The recent runs are failing because of a permission error.

chore: fix `sync.yml` permissions

---

sources/commands/Enable.ts

As option `--install-directory` is a single specified directory, so the command description is better to be `directory`
```
━━━ General commands ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
corepack disable [--install-directory #0] ...
Remove the Corepack shims from the install directory
corepack enable [--install-directory #0] ...
Add the Corepack shims to the install directories
corepack hydrate [--activate] <fileName>
Import a package manager into the cache
corepack prepare [--activate] [--all] [--json] [-o,--output] ...
Generate a package manager archive
You can also print more details about any of these commands by calling them with
the `-h,--help` flag right after the command name.
```

doc: update directories to directory in corepack --help

---

.github/workflows/ci.yml
package.json
yarn.lock

- closes https://github.com/nodejs/corepack/issues/592
1. Node.js 21 entered [end-of-life](https://github.com/nodejs/release#release-schedule) on Jun 6, 2024. It is however still allowed by:
https://github.com/nodejs/corepack/blob/0ae3c3c1f5cbbc7fd14b7be8e71e8472215c68d2/package.json#L12-L14
2. The workflow [ci.yml](https://github.com/nodejs/corepack/blob/main/.github/workflows/ci.yml) continues to test it:
https://github.com/nodejs/corepack/blob/0ae3c3c1f5cbbc7fd14b7be8e71e8472215c68d2/.github/workflows/ci.yml#L47-L52
3. There is no version of [better-sqlite3](https://www.npmjs.com/package/better-sqlite3) (used in `devDependencies`) which supports both Node.js 21 and 23, so continuing support for Node.js 21 blocks supporting Node.js 23.
- Drop support for Node.js 21 in …

chore!: remove Node.js 21.x from the range of supported versions

---

CONTRIBUTING.md

[Adding a new package manager](https://github.com/nodejs/corepack/blob/main/CONTRIBUTING.md#adding-a-new-package-manager) contains text with repeated words / phrases:
> - [`package.json`](https://github.com/nodejs/corepack/blob/main/package.json) to add to add the added shims to the list of
`"publishConfig/bin"` and `"executableFiles"`,
with add / add / added
> - [`package.json`](https://github.com/nodejs/corepack/blob/main/package.json) to add new shims to the list of
`"publishConfig/bin"` and `"executableFiles"`,

docs: fix new shims contributing typo

---

CONTRIBUTING.md
README.md

- closes #603
Add information to the following document~~s~~ regarding use of the npm [debug](https://www.npmjs.com/package/debug) module by setting the related environment variable `DEBUG=corepack` to enable additional debug logging:
- [README](https://github.com/nodejs/corepack/blob/main/README.md) document and
- ~~[CONTRIBUTING](https://github.com/nodejs/corepack/blob/main/CONTRIBUTING.md) document~~ Edit: removed this change

docs: add DEBUG=corepack logging instructions

---

config.json

- closes https://github.com/nodejs/corepack/issues/613
Updates https://github.com/nodejs/corepack/blob/9dfbe180036d5e5b00c5c074dda5b44ce7a2c7be/config.json#L165-L175 to align with currently published keys from https://registry.npmjs.org/-/npm/v1/keys:
```json
{
"keys": [
{
"expires": "2025-01-29T00:00:00.000Z",
"keyid": "SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA",
"keytype": "ecdsa-sha2-nistp256",
"scheme": "ecdsa-sha2-nistp256",
"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="
},
{
"expires": null,
"keyid": "SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U",
"keytype": "ecdsa-sha2-nistp256",
"scheme": "ecdsa-sha2-nistp256",
"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+ …
```

fix: update npm registry keys

---

CONTRIBUTING.md

- addresses documentation related to #598
- As described in issue https://github.com/nodejs/corepack/issues/598, if the instructions in [CONTRIBUTING](https://github.com/nodejs/corepack/blob/main/CONTRIBUTING.md) are followed to clone the repo, install dependencies with Yarn and then build with Yarn, these steps fail if running on a Microsoft Windows operating system and the repo has been cloned to a drive which is not the user's `HOMEDRIVE`.
- Pending the implementation of Yarn feature request https://github.com/yarnpkg/berry/issues/4030, [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp) is not compatible with the above Windows configuration.
- The [corepack repo](https://github.com/nodejs/corepack) is currently configured to use [Yarn …

docs: add contributor windows os non-homedrive usage

---

package.json

This is a housekeeping PR to update the repo's own `packageManager` record in [package.json](https://github.com/nodejs/corepack/blob/main/package.json) from [yarn@4.3.1](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.3.1) (released Jun 21, 2024) to [yarn@4.6.0](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.6.0) (current `latest` released Dec 29, 2024) using Corepack's own command
```shell
corepack up
```
It also updates the `packageManager` hash for `yarn` from `sha224` to `sha512`, bringing it in line with the currently used default hash type.

chore: update yarn to 4.6.0

---

package.json
yarn.lock

`supports-color` and `which` now require Node.js 18.17+ – just like Corepack.
Also bumping esbuild and vitest while we're at it

chore(deps): bump all dependencies

---

README.md

fix(doc): fix link to proxy library

---

README.md

- relates to #305
Add a sub-section "Update Corepack using npm" to the [README](https://github.com/nodejs/corepack/blob/main/README.md) document, [Manual installs](https://github.com/nodejs/corepack/blob/main/README.md#manual-installs) section.
It covers a regular update with `npm install -g corepack@latest` and describes how to update Corepack if Node.js has been installed on Windows using a Windows Installer `.msi` package, which requires disabling the "corepack manager" feature before attempting a Corepack update.

docs: add instructions to update corepack

---

sources/Engine.ts
sources/types.ts
tests/main.test.ts

Fixes: https://github.com/nodejs/corepack/issues/625

fix: do not resolve fallback descriptor when `packageManager` is defined

---

tests/_registryServer.mjs

This change almost halves the time it takes to run `tests/main.test.ts` from 150s to 70s.

Make e2e test faster, don’t keep http connections alive

---

tests/main.test.ts

We correct expectations against CLI output that use regular expressions. We fix tests that are easy to fix and mark tests as failing otherwise.

Fix or mark false-positives in end-to-end tests

---

tests/main.test.ts

Ranges and tags are not the same thing, it can be useful to have two different tests in case only one of them fail.

chore(tests): split invalid_signature test in two

---

.github/workflows/ci.yml

- Due to issue https://github.com/nodejs/corepack/issues/597 Windows was excluded from testing in Node.js 23 inside [.github/workflows/ci.yml](https://github.com/nodejs/corepack/blob/main/.github/workflows/ci.yml).
The above issue is no longer reproducible.
Remove the exclusion of running CI tests on Windows under Node.js 23 from the workflow [.github/workflows/ci.yml](https://github.com/nodejs/corepack/blob/main/.github/workflows/ci.yml).

ci: enable node 23 ci tests for windows

---

sources/Engine.ts
sources/commands/Base.ts
sources/commands/deprecated/Prepare.ts

The adjective [explicit](https://dictionary.cambridge.org/dictionary/english/explicit) is used incorrectly as a verb.
- The issue was noticed in #643 although it does not originate from this PR.
Replace the use of "explicit" using the transitive verb [specify](https://dictionary.cambridge.org/dictionary/english/specify).
This affects only a comment and error messages.

fix: replace explicit with specify as verb

---

tests/main.test.ts

Remove temporary home directories in test teardown. I actually ran out of space a couple of times and before I could remove the temporary directories I had to change the permissions.

Remove temporary home directories in test teardown

---

tests/Up.test.ts
tests/Use.test.ts

Follow up of https://github.com/nodejs/corepack/pull/662

chore(tests): remove temporary directories in test teardown

---

sources/Engine.ts
sources/commands/Base.ts
sources/commands/deprecated/Prepare.ts
sources/specUtils.ts
tests/Use.test.ts

`corepack use …` should not throw because it doesn't like the previous `packageManager` value, it's going to overwrite it anyway.

fix(use): do not throw on invalid `packageManager`

---

README.md
sources/commands/Base.ts
sources/specUtils.ts
tests/Up.test.ts
tests/Use.test.ts
tests/main.test.ts

This implementation of `devEngines` support in this PR is limited to `packageManager` only, only one `packageManager` can be specified, ~the `onFail` field is ignored~ EDIT: I've added support for the `onFail` field, supporting the same values as npm.
Fixes: https://github.com/nodejs/corepack/issues/567

feat: add limited support for `devEngines`

---

README.md
sources/npmRegistryUtils.ts
sources/specUtils.ts
sources/types.ts
tests/main.test.ts

This would allow project author to customize the behavior of Corepack – with the recent incident related to npm registry key rotation, it show how it would be useful to override the built-in values. It could also be used to disable auto pinning at a project level.
It's also a first step towards allowing specifying ranges in the `package.json` (see #634), which has been requested for a long long time (https://github.com/nodejs/corepack/issues/95).
Fixes: https://github.com/nodejs/corepack/issues/628

feat: add support for `.corepack.env`

---

sources/Engine.ts

Fix typo in
https://github.com/nodejs/corepack/blob/679bcefda571e99bcf021d48b502e56d66d6eac0/sources/Engine.ts#L291
should be `packageManager`
The text was added by https://github.com/nodejs/corepack/pull/538

chore: debug text typo

---

.github/workflows/publish.yml
package.json

Latest version of Yarn added support for that, previous attempt in https://github.com/nodejs/corepack/pull/520 failed probably for a permission issue.

chore(publish): add `--provenance`

---

.github/workflows/ci.yml
package.json

- closes https://github.com/nodejs/corepack/issues/716
Referring to the [Node.js release schedule](https://github.com/nodejs/release#release-schedule) the following release transitions have occurred:
| Node.js | Status      | Date       |
| ------- | ----------- | ---------- |
| `18.x`  | End-of-Life | 2025-04-30 |
| `23.x`  | End-of-Life | 2025-06-01 |
| `24.x`  | Release     | 2025-05-06 |
1. In [package.json](https://github.com/nodejs/corepack/blob/main/package.json) remove `18.x`, remove `23.x`, continue to include `24.x` and above:
```json
"engines": {
"node": "^20.10.0 || ^22.11.0 || >=24.0.0"
},
```
2. In [.github/workflows/ci.yml](https://github.com/nodejs/corepack/blob/main/.github/workflows/ci.yml) remove `18.x`, remove `23.x`, add `24.x` with Windows exclusion, due to issue …

chore!: remove Node.js 18.x and 23.x usage, add 24.x

---

README.md

docs(corepack-version): reference node 24 as latest default

---

sources/httpUtils.ts

Update the registry origin check to use the correct URL object for comparison.

Fix incorrect registry origin check
