nodejs/corepack

- README.md
https://github.com/nodejs/node/releases/tag/v14.19.0
https://nodejs.org/dist/latest-v14.x/docs/api/corepack.html
> Add Node.js 14.19.0 to readme

- README.md
The readme was missing a few environment variables.
Fixes #55
> Adds missing environment variables to the README

- .github/workflows/ci.yml
- .github/workflows/sync.yml
- config.json
- tests/main.test.ts
Fixes #85 
It doesn't automatically publish the update yet (I don't have the permissions to add secrets to the GH repo).
> chore: auto-sync package manager versions

- config.json
Upgrade package manager versions to their latest releases.
> Updates package manager versions

- yarn.lock
Apply all minor and patch updates available for the semvere-ranges we are targeting.
> chore: bump npm deps

- .github/workflows/publish.yml
This PR adds a workflow to automatically publish new versions each time we modify the `version` field in the `package.json`.
> ci: add a publish workflow

- tests/main.test.ts
Refs: https://github.com/nodejs/corepack/pull/137
> test: fix tests when default versions contain hashes

- tests/main.test.ts
ref https://github.com/nodejs/corepack/pull/165#discussion_r961010680
> test: refactor with expect.stringMatching()

- CONTRIBUTING.md
- README.md
Refs: https://github.com/nodejs/corepack/issues/198#issuecomment-1286085756
> chore(doc): fix outdated "Contributing" section

- .github/workflows/publish.yml
Fixes: https://github.com/nodejs/corepack/issues/235
> chore(ci): add prebuilt executable to GitHub release

- .github/workflows/publish.yml
Refs: https://github.com/nodejs/corepack/pull/243#discussion_r1198689144
> chore(ci): add whole package archive to GH release

- package.json
- yarn.lock
Simple housekeeping before the release
> chore: bump npm dependencies

- .yarn/sdks/eslint/lib/unsupported-api.js
- .yarn/sdks/eslint/package.json
- .yarn/sdks/typescript/package.json
- package.json
- yarn.lock
This diff upgrades TS and the TS SDK.
> Upgrades TypeScript

- sources/commands/Base.ts
These imports were unused so I removed them
> chore: remove unused imports

- tests/main.test.ts
As suggested here: https://github.com/nodejs/corepack/pull/456#discussion_r1566258766
> Tests: Handle windows path formatting more gracefully

- README.md
Similar to the one done in https://github.com/nodejs/next-10
> docs: add link to OpenJS slack channel

- tests/main.test.ts
- yarn.lock
Refs: https://github.com/yarnpkg/berry/pull/6226
> chore: do not use outdated `fs.rmdir` API

- .github/workflows/publish.yml
Refs: https://github.com/googleapis/release-please-action#workflow-permissions
> chore: fix permissions in `publish.yml`

- .github/workflows/publish.yml
> ci: move away from archived `google-github` action

- sources/main.ts
Fixes: https://github.com/nodejs/corepack/issues/585
> fix: only print message for `UsageError`s

- tests/setupTests.ts
Refs: https://github.com/nodejs/corepack/pull/605#discussion_r1923583660
> chore(tests): do not fail tests when `DEBUG` is set in the env

- .yarn/sdks/eslint/bin/eslint.js
- .yarn/sdks/eslint/lib/api.js
- .yarn/sdks/eslint/lib/unsupported-api.js
- .yarn/sdks/eslint/package.json
- .yarn/sdks/typescript/bin/tsc
- .yarn/sdks/typescript/bin/tsserver
- .yarn/sdks/typescript/lib/tsc.js
- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/sdks/typescript/lib/tsserverlibrary.js
- .yarn/sdks/typescript/lib/typescript.js
- .yarn/sdks/typescript/package.json
- package.json
- yarn.lock
This commit bumps TypeScript to a new release. I had some issues in VSCode which seem solved on new releases.
> Bumps TypeScript to 5.7
